/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package seniorSoftwareDeveloperTestAltair;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.List;

import org.junit.Test;

import seniorSoftwareDeveloperTestAltair.fileUtils.FileUtils;

public class WordCounterTest {
    @Test public void testSomeLibraryMethod() throws IOException {
        WordCounter classUnderTest = new WordCounter();
        List<String> lines = Files.readAllLines(Paths.get(FileUtils.getResourcesTestFilePath("Text.txt")));
		lines.stream().forEach(x-> System.out.println(x));
    }
}
