/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package seniorSoftwareDeveloperTestAltair.processors;

import org.junit.Test;
import seniorSoftwareDeveloperTestAltair.fileUtils.FileUtils;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.List;

public class WordCounterTest {

    public WordCounter classUnderTest = new WordCounter(true);
    private String textFilename = "Text.txt";

    @Test public void testSomeLibraryMethod() throws IOException {
        List<String> lines = Files.readAllLines(Paths.get(FileUtils.getResourcesTestFilePath("Text.txt")));
		lines.stream().forEach(x-> System.out.println(x));
    }

    @Test public void testWordCounterIgnoreCase() {
        classUnderTest.countWords(textFilename, true);
    }

    @Test public void testWordCounter() {
        classUnderTest.countWords(textFilename, false);
    }

    @Test public void testWordCounterEmptyFile() {
        classUnderTest.countWords("EmptyText.txt", true);
    }

    @Test public void tetWordCounterNonExistingFile() {
        classUnderTest.countWords("Nofile.txt", true);
    }

    @Test public void tetWordCounter100WordFile() {
        classUnderTest.countWords("LoreIpsum.txt", true);
    }

    @Test public void tetWordCounter500WordFile() {
        classUnderTest.countWords("500WordText.txt", true);
    }

    @Test public void tetWordCounterNullFile() {
        classUnderTest.countWords(null, true);
    }

}
